### ISSUE TITLE
owl:sameAs with dbpedia

### ISSUE THREAD

**Issue by retog** [zazuko/fso-lod#16]
http://classifications.data.admin.ch/municipality/296 has no owl:sameAs but http://classifications.data.admin.ch/municipality/174 has one. This seems to be quite arbitrary and raises the question if owl:sameAs is the right property (as the two resources are probably not the same according to the FSO).

**Comment by ktk** [comment]
This now all changed in https://github.com/zazuko/fso-lod/commit/7b1955847f07277fed54b877cccdcdcab7945971

We use `owl:sameAs` for Wikidata but not anymore for DBpedia, there we have `rdfs:seeAlso` instead, as well as for Swisstopo.
