### ISSUE TITLE
Interlink to Wikidata

### ISSUE THREAD

**Issue by ktk** [zazuko/fso-lod#17]
Won't be that easy, see https://paper.dropbox.com/doc/Municipality-Index-and-Wikidata-uQDkfsxIwinJd8LEh58SD

**Comment by l00mi** [comment]
I don't see the problem, can you elaborate?

**Comment by ktk** [comment]
Implemented with https://github.com/zazuko/fso-lod/commit/32f97a0bd5f8aeaddb74ed92835f9dd3df7dabd3
