### ISSUE TITLE
Provide VoID & DCAT metadata

### ISSUE THREAD

**Issue by ktk** [zazuko/fso-lod#3]
As reference:

DCAT & VoID presentation: http://richard.cyganiak.de/2011/gld/gld-dcat-and-void.pdf

DCAT vs VoID: https://lists.w3.org/Archives/Public/public-gld-comments/2012Apr/0028.htm

**Comment by l00mi** [comment]
Also http://www.egovernment.ch/umsetzung/00881/00883/01112/index.html?lang=en

Package M8

**Comment by l00mi** [comment]
prov-o

**Comment by ktk** [comment]
Which is here http://www.w3.org/TR/prov-o/

**Comment by ktk** [comment]
And another reference https://blog.semantic-web.at/2015/12/02/ready-to-connect-to-the-semantic-web-now-what/

**Comment by ktk** [comment]
Now basically done but moved to https://github.com/zazuko/lindas-datasets
