### ISSUE TITLE
SPARQL not working

### ISSUE THREAD

**Issue by retog** [zazuko/fso-lod#4]
The "SPARQL Endpoint" linked in the README is:
A) Not a SPARQL Enpoint but just a YASGUI sparql query editor
B) It is not working as it sends the SPARQL Query to `http://localhost:8080/sparql`

**Comment by ktk** [comment]
Not sure what you are talking about, on data.admin.ch it says the web interface is at /sparql while the endpoint is /query. YASGUI indeed doesn't have the correct config yet, need to figure out how to properly do that with the npm install of YASGUI.
