### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by ktk** [zazuko/fso-lod#8]

**Comment by ktk** [comment]
Lizenz fehlt noch. Möglichkeiten (via Pascal):
- https://spdx.org/licenses/ (Hat das RDF?)
- http://rdflicense.linkeddata.es/

**Comment by retog** [comment]
I would suggest MIT for the code (scripts) - but this is so mininimal that we can leave it as it is.

As for the data:

– its use is not restricted for reasons to do with data protection law, copyright
law or information protection law and it can be freely reused by third
parties (open government data, OGD).

So "licensing" the data is not something we should (or could) do and far less conditioning the licensing to any condition as clearly also the RDF version of the data if OGD.

I suggest to keep thing simple and just close the issue.

**Comment by ktk** [comment]
Agreed, we cannot do anything here, closing
